from io import BytesIO
from xhtml2pdf import pisa

_STYLE = """
<style>
  body { font-family: Helvetica, sans-serif; color: #1c2431; font-size: 11pt; }
  h1 { font-size: 18pt; margin-bottom: 0; }
  .muted { color: #5b6472; font-size: 9pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th { text-align: left; border-bottom: 1px solid #1c2431; padding: 6px 4px; font-size: 9pt; }
  td { padding: 6px 4px; border-bottom: 1px solid #e1ddd5; }
  .total-row td { font-weight: bold; border-top: 2px solid #1c2431; border-bottom: none; }
  .badge { display: inline-block; padding: 2px 8px; background: #e5efe9; color: #2f6f5e; font-size: 9pt; }
</style>
"""


def render_pdf(html: str) -> bytes:
    buffer = BytesIO()
    result = pisa.CreatePDF(html, dest=buffer)
    if result.err:
        raise RuntimeError("Failed to generate PDF.")
    return buffer.getvalue()


def build_invoice_html(invoice: dict, client: dict, business: dict) -> str:
    return f"""
    <html><head>{_STYLE}</head><body>
      <h1>{business['name']}</h1>
      <p class="muted">Invoice</p>
      <table>
        <tr><td class="muted">Bill to</td><td>{client['name']}</td></tr>
        <tr><td class="muted">Issue date</td><td>{invoice['issue_date']}</td></tr>
        <tr><td class="muted">Due date</td><td>{invoice['due_date']}</td></tr>
        <tr><td class="muted">Status</td><td><span class="badge">{invoice['status']}</span></td></tr>
      </table>
      <table>
        <tr><th>Description</th><th>Amount</th></tr>
        <tr><td>Invoice #{invoice['id'][:8]}</td><td>{invoice['currency']} {invoice['amount']}</td></tr>
        <tr class="total-row"><td>Total</td><td>{invoice['currency']} {invoice['amount']}</td></tr>
      </table>
      <p class="muted" style="margin-top:24px;">Generated by Bharosa — a shared, verifiable ledger between you and your clients.</p>
    </body></html>
    """


def build_receipt_html(invoice: dict, client: dict, business: dict, payments: list[dict]) -> str:
    rows = "".join(
        f"<tr><td>{p['created_at']}</td><td>{p['entry_type']}</td><td>{invoice['currency']} {p['amount']}</td></tr>"
        for p in payments
    )
    return f"""
    <html><head>{_STYLE}</head><body>
      <h1>{business['name']}</h1>
      <p class="muted">Payment Receipt</p>
      <table>
        <tr><td class="muted">Received from</td><td>{client['name']}</td></tr>
        <tr><td class="muted">Invoice</td><td>#{invoice['id'][:8]}</td></tr>
        <tr><td class="muted">Status</td><td><span class="badge">Paid in full</span></td></tr>
      </table>
      <table>
        <tr><th>Date</th><th>Type</th><th>Amount</th></tr>
        {rows}
        <tr class="total-row"><td colspan="2">Total received</td><td>{invoice['currency']} {invoice['amount']}</td></tr>
      </table>
      <p class="muted" style="margin-top:24px;">This receipt confirms payment recorded on Bharosa's shared ledger.</p>
    </body></html>
    """


def build_statement_html(client: dict, business: dict, invoices: list[dict], ledger_entries: list[dict]) -> str:
    invoice_rows = "".join(
        f"<tr><td>#{inv['id'][:8]}</td><td>{inv['issue_date']}</td><td>{inv['due_date']}</td>"
        f"<td>{inv['currency']} {inv['amount']}</td><td>{inv['status']}</td></tr>"
        for inv in invoices
    )
    ledger_rows = "".join(
        f"<tr><td>{e['created_at']}</td><td>{e['entry_type']}</td><td>{e['amount'] or '-'}</td><td>{e['actor']}</td></tr>"
        for e in ledger_entries
    )
    return f"""
    <html><head>{_STYLE}</head><body>
      <h1>{business['name']}</h1>
      <p class="muted">Account Statement — {client['name']}</p>

      <h3>Invoices</h3>
      <table>
        <tr><th>Invoice</th><th>Issued</th><th>Due</th><th>Amount</th><th>Status</th></tr>
        {invoice_rows or '<tr><td colspan="5">No invoices on record.</td></tr>'}
      </table>

      <h3 style="margin-top:24px;">Ledger activity</h3>
      <table>
        <tr><th>Date</th><th>Entry</th><th>Amount</th><th>Actor</th></tr>
        {ledger_rows or '<tr><td colspan="4">No activity recorded.</td></tr>'}
      </table>

      <p class="muted" style="margin-top:24px;">Auto-generated from Bharosa's shared ledger, verifiable by both parties.</p>
    </body></html>
    """